/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KlNearbyToothbrush {
    }
    interface KlPanel {
    }
    interface MyComponent {
        /**
          * Render a circle button
         */
        "circle": boolean;
        /**
          * Disables the button
         */
        "disabled": boolean;
        /**
          * Render a ghost button
         */
        "ghost": boolean;
        /**
          * The button's size
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The button's variant
         */
        "variant": 'primary' | 'neutral' | 'success' | 'warn' | 'text';
    }
}
declare global {
    interface HTMLKlNearbyToothbrushElement extends Components.KlNearbyToothbrush, HTMLStencilElement {
    }
    var HTMLKlNearbyToothbrushElement: {
        prototype: HTMLKlNearbyToothbrushElement;
        new (): HTMLKlNearbyToothbrushElement;
    };
    interface HTMLKlPanelElement extends Components.KlPanel, HTMLStencilElement {
    }
    var HTMLKlPanelElement: {
        prototype: HTMLKlPanelElement;
        new (): HTMLKlPanelElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "kl-nearby-toothbrush": HTMLKlNearbyToothbrushElement;
        "kl-panel": HTMLKlPanelElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KlNearbyToothbrush {
    }
    interface KlPanel {
    }
    interface MyComponent {
        /**
          * Render a circle button
         */
        "circle"?: boolean;
        /**
          * Disables the button
         */
        "disabled"?: boolean;
        /**
          * Render a ghost button
         */
        "ghost"?: boolean;
        /**
          * The button's size
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The button's variant
         */
        "variant"?: 'primary' | 'neutral' | 'success' | 'warn' | 'text';
    }
    interface IntrinsicElements {
        "kl-nearby-toothbrush": KlNearbyToothbrush;
        "kl-panel": KlPanel;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kl-nearby-toothbrush": LocalJSX.KlNearbyToothbrush & JSXBase.HTMLAttributes<HTMLKlNearbyToothbrushElement>;
            "kl-panel": LocalJSX.KlPanel & JSXBase.HTMLAttributes<HTMLKlPanelElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
